### PR TITLE
Ability to get/set eco mode

### PR DESCRIPTION
**Pull request by Ekman**
Ability to get/set eco mode.

Let me know if you have any comments or suggestions.

### CODE REVIEW

**Comment by Phype** [comment]
I'm fine with the PR. One question: Have you tested this on both version of the Purei9 Robot? I'm asking because the Purei9.2 has 3 Power Modes (Eco/Normal/Power) while the old one only has 2. I only have the old one to test.

**Comment by Ekman** [comment]
I can test this on the newer model later today. I have them both nowadays.

**Comment by Phype** [comment]
I reworked the code because it did not work with the newer model (i got access to one to test). It should now work with both versions, feel free to test. Also, if you want to include this functionality in the homeassistant integration and want me to make a release to pypy, ping me and i'll try to do it.

**Comment by Ekman** [comment]
Appreciate it!

Yes, a release to pypip would be awesome.

**Comment by Phype** [comment]
> Yes, a release to pypip would be awesome.

I've pushed version 0.0.4.

**Comment by Ekman** [comment]
Thank you

**Pull request merged**
